### ISSUE TITLE
blank id on package creation

### ISSUE THREAD

**Issue by durgesh077** [metacall/faas#19]
![image](https://user-images.githubusercontent.com/66236446/218514443-2a4eadec-cd14-4a09-b7d3-0d4144feee5e.png)
![image](https://user-images.githubusercontent.com/66236446/218514579-35d31b1c-df18-4382-988b-9d7024e07d62.png)

**Comment by Creatoon** [comment]
@durgesh077 You are sending half data and its not expected, also you are sending the wrong key for zip file, it should be blob.

but the correct way is
```
{
	id: string;
	type?: string;
	jsons: MetaCallJSON[];
	runners?: string[];
	path: string;
}
```

Although thanks for reporting this, I am already working on the way to verify data coming from user request, it will be patched soon.

**Comment by ashutosh887** [comment]
Hi @Creatoon 
I would like to work on this Issue.

**Comment by Creatoon** [comment]
@ashutosh887 how will you proceed?

**Comment by durgesh077** [comment]
@Creatoon I have a view point. I had already pushed a PR related to it. It was based on random id generation and then checking if the randomly generated has already been assigned. If not then fine, else I was adding a stub. We can add an optional parameter into formdata which provides id from user end. If user provides it, then we'll try to assign  it else randomly generated id will work fine.

**Comment by durgesh077** [comment]
https://github.com/metacall/faas/pull/17  this my PR

**Comment by durgesh077** [comment]
or we can make ID by adding some required stub at the end of zip file name:- 
Like it file name is **Func.zip** we can try Func-stub1 , Func-stub2 so on where stub is randomly generated

**Comment by Creatoon** [comment]
@durgesh077 At the end, users will be using with @metacall/deploy CLI to interact with this FAAS, and It will auto generate the id for you, if user did not provided it.

And we should validate the incoming form data, if it consists or fields or not, if not, we will simply notify user by throwing an error, instead of generating names randomly.

**Comment by durgesh077** [comment]
Yes , but finding new id that has not been used may find user but annoying. That's why

**Comment by Creatoon** [comment]
Thanks @durgesh077, we will be needing unique name and will surely tell you how to proceed with this, for now we have to implement few endpoints that will support your issue.

**Comment by durgesh077** [comment]
Sure, You can assign me some of the task which you like .I'll be happy to work with you. I have good experience at backend.

**Comment by viferga** [comment]
The id is a required field, we are trying to mimic the behavior of the [FaaS](https://dashboard.metacall.io).
We obtain the name of the deployment from the current directory name or from the repository url when deploying from repo.
