### ISSUE TITLE
Build proper CI system. 

### ISSUE THREAD

**Issue by HeeManSu** [metacall/faas#31]

**Comment by abhaysinghs772** [comment]
hey @HeeManSu @viferga could you please explain to me, what has to be done in this issue since the issue is not descriptive enough.

**Comment by viferga** [comment]
> hey @HeeManSu @viferga could you please explain to me, what has to be done in this issue since the issue is not descriptive enough.

Basically implementing the integration tests: https://github.com/metacall/faas/blob/16c492fc6dd3aaa0cae9928f432f9bff0c0bc11a/.github/workflows/ci.yml#L49

Check the test folder and the docker files.
