### ISSUE TITLE
Implement logs

### ISSUE THREAD

**Issue by HeeManSu** [metacall/faas#32]
This will retrieve and show the logs of a deploy.

**Comment by viferga** [comment]
It would be interesting to implement coloring by worker and not just by stdout/stderr.

https://github.com/metacall/faas/commit/336022cca0a3778ddc46f66be8cb45ba5516959a

**Comment by Creatoon** [comment]
Reopening the issue, as there are more improvements in the logs itself, will list it down, once I gather all the info.

Thanks

**Comment by HeeManSu** [comment]
https://github.com/metacall/faas/pull/44

The above PR includes a few improvements.

**Comment by viferga** [comment]
I consider this issue done.
