### ISSUE TITLE
Implement Deploy delete 

### ISSUE THREAD

**Issue by HeeManSu** [metacall/faas#33]
This will deletes the deploy and the zip.

**Comment by aakritiawasthi** [comment]
Hello everyone, Can you assign this issue to me, this issue is open for a week and I also have some code ready, if you could assign it to me I will pr.

Thanks

**Comment by durgesh077** [comment]
These APIs were already done, as in last GSOC i have made them for project

**Comment by HeeManSu** [comment]
> These APIs were already done, as in last GSOC i have made them for project

They are not there in the faas. Can you please share your project

**Comment by HeeManSu** [comment]
@aakritiawasthi @Creatoon  hey, this issue is assigned to me.

**Comment by HeeManSu** [comment]
@viferga 
https://github.com/metacall/faas/pull/37

**Comment by Creatoon** [comment]
Hey @HeeManSu 

We really value what you bring to the team. But could you please avoid tagging all the mentors in messages.

Right now, there's some conflict, and it's important to address it nicely. Let's try not to leave issues unresolved for too long. It helps keep things moving smoothly.

About the PRs, they look identical, so we've decided to go with the first one by @aakritiawasthi 

We can't let anyone take all the issues and leave those to idle stage.

Thanks for understanding. Let's keep working well together!
